import random
from aalpy.utils import generate_random_dfa

"""
This script creates the Automata data where we define each type of automaton DFA, NFA and ε-NFA
We define the number of states, state IDs, input alphabets and control tokens.
The Automata are generated by using the 'aalpy' library.
We tokenizes the automata graphs so that the transformer can process it.
"""

# Vocabulary configuration
alphabet_len = 6   # Input Alphabet Σ
Max_states = 100    # Maximum number of states allows in a generated automaton

# Define unique tokens for State IDs, Targets and input alphabet
inputs = [f'input_{x}' for x in range(alphabet_len)]
State_ID = [f'ID_{i}' for i in range(Max_states)] # Used for state definitions
State_Targets = [f'Target_{i}' for i in range(Max_states)] # Used for transition destinations

# Control tokens used to transform the graph into a sequence token
# PAD used for padding to maintain the same size
# epsilon to represent the ε-NFA
# START token to represent the initial state
# ACCEPT token to represent the final state
# TRANSITION token to represent the transitions between 2 state and with which input
# SEP token to specify the end of a sequence without it we can have a singular long sequence which makes it 
# harder for the transformer to check whether it is 1 automaton or many automata
Special_tokens = ['PAD','epsilon', 'START', 'ACCEPT', 'TRANSITION', 'SEP']
Token_combo = State_ID + State_Targets + inputs + Special_tokens

# Map tokens ot integer indices for the model
Tokens = {}
for i, token in enumerate(Token_combo):
    Tokens[token] = i

PAD_IDX = Tokens['PAD']
VOCAB_SIZE = len(Token_combo)

def Automata(type):
    """
    Generates a random automaton of a specific type and linearize it.
    
    We start by generating a base DFA using the aalpy library then we randomly map states to unique
    ID and Target tokens.
    
    If it is an NFA or ε-NFA then we inject either a non-deterministic transition or an ε transition.
    
    Sequence = [START, Initial_State, State_1, [Transitions], SEP, ...]
    """
    
    # Determine the size and base input alphabet
    num_states = random.randint(10, Max_states)
    input_alpha= [str(i) for i in range(alphabet_len)]
    
    # Generate a base DFA
    # This ensure that we have a reachable and connected graph
    automaton = generate_random_dfa(num_states, input_alpha)
    
    # Randomly assign ID and Target tokens to states
    available_indices = list(range(Max_states))
    
    # Shuffle the indices so the model can't learn that "State 0" is always "ID 0"
    random.shuffle(available_indices)
    
    state_id_val = {}        # Maps internal state object -> ID token index
    state_target_val = {}    # Maps internal state object -> Target token index
    
    for i, state in enumerate(automaton.states):
        state_id_val[state] = Tokens[f'ID_{available_indices[i]}'] # used when we are DESCRIBING the state
        state_target_val[state] = Tokens[f'Target_{available_indices[i]}'] # used when POINTING to the state in the transition
    
    # Convert the automaton into a dictionary adjacency list
    adj = {}
    for state in automaton.states:
        adj[state] = {inp: [dest] for inp, dest in state.transitions.items()} #adj[source_state][input_symbol] = [list of destination states]
    
    # If the automaton is not a DFA then the DFA rule breaks
    if type in ['NFA', 'EPS_NFA']:
        # Add a random non-deterministic transitions
        num_extra = random.randint(num_states // 2, num_states)
        for _ in range(num_extra):
            src = random.choice(automaton.states)
            inp = random.choice(input_alpha)
            dest = random.choice(automaton.states)
            if dest not in adj[src][inp]:
                adj[src][inp].append(dest)
        
        # Add an ε transitions 
        if type == 'EPS_NFA':
            for _ in range(random.randint(1,10)):
                src = random.choice(automaton.states)
                dest = random.choice(automaton.states)
                if 'epsilon' not in adj[src]:
                    adj[src]['epsilon'] = []
                if dest not in adj[src]['epsilon']:
                    adj[src]['epsilon'].append(dest)
        
    # Convert the graph into a sequence of tokens
    # Start the sequence with a structural START token and the entry point ID
    sequence = [Tokens['START'], state_id_val[automaton.initial_state]]
    
    # Shuffle the list of states before writing them to the sequence
    # This forces the model to learn the logic of transitions rather than the order in which states appear in the text.
    shuffled_states = list(automaton.states)
    random.shuffle(shuffled_states)
    
    for state in shuffled_states:
        # Identify the state being defined
        sequence.append(state_id_val[state])
        
        # Id teh state is an accepting state then mark it
        if state.is_accepting:
            sequence.append(Tokens['ACCEPT'])
        
        # We list all the possible transitions for this state
        for inp, targets in adj[state].items():
            # Choose the correct input token
            token_inp = Tokens['epsilon'] if inp == 'epsilon' else Tokens[f'input_{inp}']
            
            sequence.append(Tokens['TRANSITION']) # Mark it as a new transition
            sequence.append(token_inp)            # Mark the input symbol
            for dest in targets:
                sequence.append(state_target_val[dest])
        
        # End of the current state definition
        sequence.append(Tokens['SEP'])

    return sequence

# Create a sample to use it later for generating the dataset.
def sample():
    types = ['DFA', 'NFA']
    selected_type = random.choice(types)
    sequence = Automata(selected_type)
    
    return sequence, selected_type
